service: product-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  # dbConfig.json with private data was not added to repo
  environment:
    PG_HOST: ${file(dbConfig.json):PG_HOST}
    PG_PORT: ${file(dbConfig.json):PG_PORT}
    PG_DATABASE: ${file(dbConfig.json):PG_DATABASE}
    PG_USERNAME: ${file(dbConfig.json):DB_USER}
    PG_PASSWORD: ${file(dbConfig.json):DB_PASS}

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  getAllProducts:
    handler: handler.getProductsHandler
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductById:
    handler: handler.getProductByIdHandler
    events:
      - http:
          path: product/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true

  addProduct:
    handler: handler.addProductHandler
    events:
      - http:
          path: product
          method: post
          cors: true
